#! /bin/sh

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/home/pi/mirrorpy/mirror.py
DAEMON_NAME=mirrorpy
DAEMON_USER=root
PIDFILE=/var/run/mirrorpy.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Demarrage du service $DAEMON_NAME"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --exec $DAEMON
    log_end_msg $?
   ;;
  stop)
    log_daemon_msg "Arret du service $DAEMON_NAME"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
   ;;
  restart)
     $0 stop
     $0 start
   ;;
  status)
     status_of_proc -p $PIDFILE $DAEMON $DAEMON_NAME && exit 0 || exit $?
   ;;
 *)
   echo "Utilisation : /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
   exit 1
  ;;
esac

exit 0
